apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-api-deployment
  labels:
    app: pay-api-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pay-api-app

  template:
    metadata:
      labels:
        app: pay-api-app
    spec:
      containers:
        - name: pay-api-app
          #this docker image url set after main.yml file processing completed.
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: RDS_HOSTNAME
              value: "qrtsrds.czoqs42aucms.ap-southeast-1.rds.amazonaws.com"
            - name: RDS_USERNAME
              value: "postgres"
            - name: RDS_PASSWORD
              value: "postgres"
            - name: RDS_PORT
              value: "5432"
            - name: RDS_DB_NAME
              value: "qr_pay_db"
            - name: ACTIVEMQ_BROKER_URL
              value: "ssl://b-0a3cb9ea-788b-4bde-933e-dec0c237dad4-1.mq.ap-southeast-1.amazonaws.com:61617"
            - name: ACTIVEMQ_USER
              value: "amq_user"
            - name: ACTIVEMQ_PASSWORD
              value: "P@ssw0rd112233445566"
          resources:
            requests:
              cpu: "100m"  # Initial CPU request
              memory: "200Mi"  # Initial memory request
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1