apiVersion: v1
kind: Service
metadata:
  name: pay-api-service
  labels:
    app: pay-api-app
spec:
  selector:
    app: pay-api-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer